
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRExporter;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.export.JRPdfExporter;
import net.sf.jasperreports.view.JasperViewer;
import newpackage.DB;
import newpackage.Handle;



/**
 *
 * @author  Dim
 */
public class Bill extends javax.swing.JFrame {
    String id[];
    /** Creates new form Bill */
    public Bill(String[] s) {
        try {
            initComponents();
            
            setLocationRelativeTo(null);

            id = s;
            servieid.setText(id[0]);
            customername.setText(id[1]);
            date.setText(id[2]);
            vehiclenumber.setText(id[3]);
            vehicle.setText(id[4]);
            km.setText(id[5]);
            fuelfiltercode.setText(id[6]);
            oilfiltercode.setText(id[7]);
            airfiltercode.setText(id[8]);
            airconfiltercode.setText(id[9]);
            oils.setText(id[10]);
            oilpack.setText(id[11]);
            ResultSet rst = Handle.getData(DB.connect(), "select unitprice from oilfilters where vehicle = '" + vehicle.getText() + "' and oilfiltercode = '" + oilfiltercode.getText() + "' ");
            Connection con = DB.connect();

            oilfilter.setText("0.00");
            while (rst.next()) {
                oilfilter.setText(rst.getString(1));
            }


            rst = Handle.getData(DB.connect(), "select unitprice from fuelfilters where vehicle = '" + vehicle.getText() + "' and fuelfiltercode = '" + fuelfiltercode.getText() + "' ");

            fuelfilter.setText("0.00");
            while (rst.next()) {
                fuelfilter.setText(rst.getString(1));
            }



            rst = Handle.getData(DB.connect(), "select unitprice from airfilters where vehicle = '" + vehicle.getText() + "' and airfiltercode = '" + airfiltercode.getText() + "' ");

            airfilter.setText("0.00");
            while (rst.next()) {
                airfilter.setText(rst.getString(1));
            }


            rst = Handle.getData(DB.connect(), "select unitprice from airconfilters where vehicle = '" + vehicle.getText() + "' and airconfiltercode = '" + airconfiltercode.getText() + "' ");

            airconfilter.setText("0.00");
            while (rst.next()) {
                airconfilter.setText(rst.getString(1));
            }

            
            rst = Handle.getData(DB.connect(), "select " + oilpack.getText() + " from oils where pdnmngd = '" + oils.getText() + "'");
            oil.setText("0.00");
            while (rst.next()) {
                oil.setText(rst.getString(1));
                System.out.println(rst.getString(1));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Bill.class.getName()).log(Level.SEVERE, null, ex);
        }
        jButton2.doClick();


    }
    
    double addTotal(String s) {
        double d=0;
        try {
            d = Double.parseDouble(s);
        } catch (Exception e) {
        }
        return d;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        pr11 = new javax.swing.JTextField();
        pr10 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        pr8 = new javax.swing.JTextField();
        pr9 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        vehiclenumber = new javax.swing.JTextField();
        servieid = new javax.swing.JTextField();
        customername = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        oilfiltercode = new javax.swing.JTextField();
        vehicle = new javax.swing.JTextField();
        km = new javax.swing.JTextField();
        fuelfiltercode = new javax.swing.JTextField();
        airconfiltercode = new javax.swing.JTextField();
        airfiltercode = new javax.swing.JTextField();
        oilfilter = new javax.swing.JTextField();
        fuelfilter = new javax.swing.JTextField();
        airconfilter = new javax.swing.JTextField();
        airfilter = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        oils = new javax.swing.JTextField();
        oilpack = new javax.swing.JTextField();
        oil = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        radiatorflush = new javax.swing.JTextField();
        greasing = new javax.swing.JTextField();
        chasis = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        engineoil = new javax.swing.JTextField();
        gearoil = new javax.swing.JTextField();
        poweroil = new javax.swing.JTextField();
        breakoil = new javax.swing.JTextField();
        battery = new javax.swing.JTextField();
        penetratingoil = new javax.swing.JTextField();
        highpressure = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        kerosene = new javax.swing.JTextField();
        diesel = new javax.swing.JTextField();
        radiatorcoolant = new javax.swing.JTextField();
        airfreshner = new javax.swing.JTextField();
        moppingclothe = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        bodywash = new javax.swing.JTextField();
        underwash = new javax.swing.JTextField();
        interiorcleaning = new javax.swing.JTextField();
        vacuumcleaning = new javax.swing.JTextField();
        hotwatercleaning = new javax.swing.JTextField();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Services"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Interior Cleaning");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel6.setText("Vacuum Cleaning");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel7.setText("Hot Water Cleaning");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jTextField6.setText("0");
        jPanel3.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, -1));

        jLabel15.setText("Body Wash");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        pr11.setText("0");
        jPanel3.add(pr11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 110, -1));

        pr10.setText("0");
        jPanel3.add(pr10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, -1));

        jLabel3.setText("Under Wash");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        pr8.setText("0");
        pr8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pr8ActionPerformed(evt);
            }
        });
        jPanel3.add(pr8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, -1));

        pr9.setText("0");
        jPanel3.add(pr9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Bill Info");
        setMinimumSize(new java.awt.Dimension(930, 720));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 600, 30, 10));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Filled Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("OilFilter Code");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, 20));

        jLabel11.setText("FuelFilter Code");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 20));

        jLabel13.setText("Km");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, 20));

        jLabel17.setText("Vehicle");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jLabel18.setText("Vehicle Number");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel19.setText("Date");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel20.setText("Customer Name");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 80, -1));

        jLabel21.setText("ServiceId");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel26.setText("AirFilter Code");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 20));

        jLabel28.setText("AirconFilter Code");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, 20));

        jLabel29.setText("Pack");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        vehiclenumber.setEditable(false);
        jPanel1.add(vehiclenumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, -1));

        servieid.setEditable(false);
        servieid.setText(" ");
        jPanel1.add(servieid, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 160, -1));

        customername.setEditable(false);
        jPanel1.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 420, -1));

        date.setEditable(false);
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, -1));

        oilfiltercode.setEditable(false);
        jPanel1.add(oilfiltercode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 160, 20));

        vehicle.setEditable(false);
        jPanel1.add(vehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 160, -1));

        km.setEditable(false);
        jPanel1.add(km, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 160, 20));

        fuelfiltercode.setEditable(false);
        jPanel1.add(fuelfiltercode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, 20));

        airconfiltercode.setEditable(false);
        jPanel1.add(airconfiltercode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 160, 20));

        airfiltercode.setEditable(false);
        jPanel1.add(airfiltercode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 160, 20));

        oilfilter.setEditable(false);
        jPanel1.add(oilfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 20));

        fuelfilter.setEditable(false);
        jPanel1.add(fuelfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 90, 20));

        airconfilter.setEditable(false);
        jPanel1.add(airconfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 90, 20));

        airfilter.setEditable(false);
        jPanel1.add(airfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 90, 20));

        jLabel27.setText("Oils");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, 20));

        oils.setEditable(false);
        jPanel1.add(oils, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 210, -1));

        oilpack.setEditable(false);
        jPanel1.add(oilpack, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 160, -1));

        oil.setEditable(false);
        jPanel1.add(oil, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 90, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 690, 370));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Items"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Chasis Lubricating");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, -1));

        jLabel24.setText("Greasing");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel25.setText("Radiator Flush");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 10));

        radiatorflush.setText("0");
        jPanel2.add(radiatorflush, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, 90, -1));

        greasing.setText("0");
        jPanel2.add(greasing, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 90, -1));

        chasis.setText("0");
        jPanel2.add(chasis, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 90, -1));

        jLabel4.setText("Engine Oil");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel8.setText("Gear Oil");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setText("Power Steering Oil");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel10.setText("Break Oil");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel16.setText("Battery Acid/ Water");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel22.setText("Penetrating Oil");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel23.setText("High Pressure");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel30.setText("Kerosene");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel31.setText("Diesel");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, -1));

        engineoil.setText("0");
        jPanel2.add(engineoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 90, -1));

        gearoil.setText("0");
        jPanel2.add(gearoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 90, -1));

        poweroil.setText("0");
        jPanel2.add(poweroil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, -1));

        breakoil.setText("0");
        jPanel2.add(breakoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 90, -1));

        battery.setText("0");
        battery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batteryActionPerformed(evt);
            }
        });
        jPanel2.add(battery, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 90, -1));

        penetratingoil.setText("0");
        jPanel2.add(penetratingoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, -1));

        highpressure.setText("0");
        jPanel2.add(highpressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 90, -1));

        jLabel33.setText("Radiator Coolant");
        jPanel2.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel32.setText("Air Freshner");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, -1, -1));

        jLabel34.setText("Mopping Clothe");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        kerosene.setText("0");
        jPanel2.add(kerosene, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 90, -1));

        diesel.setText("0");
        jPanel2.add(diesel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 90, -1));

        radiatorcoolant.setText("0");
        jPanel2.add(radiatorcoolant, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, -1));

        airfreshner.setText("0");
        jPanel2.add(airfreshner, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 90, -1));

        moppingclothe.setText("0");
        jPanel2.add(moppingclothe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 610, 290));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/printer1.png"))); // NOI18N
        jButton1.setText("     Print");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 640, 130, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator2.png"))); // NOI18N
        jButton2.setText("   ReCount");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 640, 140, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText(" Total Amount");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 590, 110, 30));

        total.setFont(new java.awt.Font("Tahoma", 1, 14));
        total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 590, 140, 30));
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 40, 10));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/1leftarrow.png"))); // NOI18N
        jButton3.setText("      Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 340, 180, 40));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AQUA ICONS FILE TEXT DOCUMENT.png"))); // NOI18N
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, -1, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Services"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setText("Body Wash");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel38.setText("Under Wash");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel39.setText("Interior Cleaning");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel40.setText("Vacuum Cleaning");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel41.setText("Hot Water Cleaning");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        bodywash.setText("0");
        jPanel4.add(bodywash, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 150, -1));

        underwash.setText("0");
        jPanel4.add(underwash, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 150, -1));

        interiorcleaning.setText("0");
        jPanel4.add(interiorcleaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 150, -1));

        vacuumcleaning.setText("0");
        jPanel4.add(vacuumcleaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 150, -1));

        hotwatercleaning.setText("0");
        jPanel4.add(hotwatercleaning, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 280, 190));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

         String reportSource="bill2.jrxml";
        String reportDest="bill2.pdf";
        
        Map<String,Object> param=new HashMap<String,Object>();
               param.put("serviceid", servieid.getText());
        param.put("date", date.getText());
        param.put("vehiclenumber", vehiclenumber.getText());
        param.put("customername", customername.getText());
        param.put("vehicle", vehicle.getText());
        param.put("km", km.getText());
        param.put("fuelfiltercode", fuelfiltercode.getText());
        param.put("oilfiltercode", oilfiltercode.getText());
        param.put("fuelfiltercode", fuelfiltercode.getText());
        param.put("airfiltercode", airfiltercode.getText());
        param.put("airconfiltercode", airconfiltercode.getText());
        param.put("oils", oils.getText());
        param.put("oilpack", oilpack.getText());
        param.put("fuelfilter", fuelfilter.getText());
        param.put("oilfilter", oilfilter.getText());
        param.put("airfilter", airfilter.getText());
        param.put("airconfilter", airconfilter.getText());
        param.put("oil", oil.getText());
        param.put("greasing", greasing.getText());
        param.put("engineoil", engineoil.getText());
        param.put("gearoil", gearoil.getText());
        param.put("poweroil", poweroil.getText());
        param.put("breakoil", breakoil.getText());
        param.put("battery", battery.getText());
        param.put("penetratingoil", penetratingoil.getText());
        param.put("highpressure", highpressure.getText());
        param.put("kerosene", kerosene.getText());
        param.put("diesel", diesel.getText());
        param.put("chasislubricating", chasis.getText());
        param.put("radiatorflush", radiatorflush.getText());
        param.put("radiatorcoolant", radiatorcoolant.getText());
        param.put("airfreshner", airfreshner.getText());
        param.put("moppingclothe", moppingclothe.getText());
        param.put("bodywash", bodywash.getText());
        param.put("underwash", underwash.getText());
        param.put("interiorcleaning", interiorcleaning.getText());
        param.put("vacuumcleaning", vacuumcleaning.getText());
        param.put("hotwatercleaning", hotwatercleaning.getText());
        param.put("total", total.getText());
        
       // param.put("address","Panadura");
        try{
            
            JasperReport jr=JasperCompileManager.compileReport(reportSource);
            
            JasperPrint jp=JasperFillManager.fillReport(jr,param,new JREmptyDataSource());
            JasperViewer.viewReport(jp);
            
            
          	JRExporter ex=new JRPdfExporter();
           	ex.setParameter(JRExporterParameter.OUTPUT_FILE_NAME, reportDest);
         		ex.setParameter(JRExporterParameter.JASPER_PRINT,jp);
         		ex.exportReport();
        	 	//Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " +reportDest);

            
        }catch(Exception e){
            System.out.print(e);
        }
        // TODO add your handling code here:
                                            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
        total.setText((Double.parseDouble(fuelfilter.getText()) + Double.parseDouble(oilfilter.getText())+ Double.parseDouble(airfilter.getText())+ Double.parseDouble(airconfilter.getText())+ Double.parseDouble(oil.getText())+ Double.parseDouble(greasing.getText())+Double.parseDouble(engineoil.getText()) + Double.parseDouble(gearoil.getText())+ Double.parseDouble(poweroil.getText())+ Double.parseDouble(breakoil.getText())+ Double.parseDouble(battery.getText())+ Double.parseDouble(penetratingoil.getText())+ Double.parseDouble(highpressure.getText())+ Double.parseDouble(kerosene.getText())+ Double.parseDouble(diesel.getText())+ Double.parseDouble(chasis.getText())+ Double.parseDouble(radiatorflush.getText())+ Double.parseDouble(radiatorcoolant.getText())+ Double.parseDouble(airfreshner.getText())+Double.parseDouble(moppingclothe.getText())+ Double.parseDouble(bodywash.getText())+ Double.parseDouble(underwash.getText())+ Double.parseDouble(interiorcleaning.getText())+ Double.parseDouble(vacuumcleaning.getText())+Double.parseDouble(hotwatercleaning.getText()))+"");
        }catch(Exception e){
           JOptionPane.showMessageDialog(this,"Count Error. Please Check Entered Data Correction","Counting Error",JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pr8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pr8ActionPerformed
       
    }//GEN-LAST:event_pr8ActionPerformed

    private void batteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batteryActionPerformed
        
}//GEN-LAST:event_batteryActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
  
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airconfilter;
    private javax.swing.JTextField airconfiltercode;
    private javax.swing.JTextField airfilter;
    private javax.swing.JTextField airfiltercode;
    private javax.swing.JTextField airfreshner;
    private javax.swing.JTextField battery;
    private javax.swing.JTextField bodywash;
    private javax.swing.JTextField breakoil;
    private javax.swing.JTextField chasis;
    private javax.swing.JTextField customername;
    private javax.swing.JTextField date;
    private javax.swing.JTextField diesel;
    private javax.swing.JTextField engineoil;
    private javax.swing.JTextField fuelfilter;
    private javax.swing.JTextField fuelfiltercode;
    private javax.swing.JTextField gearoil;
    private javax.swing.JTextField greasing;
    private javax.swing.JTextField highpressure;
    private javax.swing.JTextField hotwatercleaning;
    private javax.swing.JTextField interiorcleaning;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField kerosene;
    private javax.swing.JTextField km;
    private javax.swing.JTextField moppingclothe;
    private javax.swing.JTextField oil;
    private javax.swing.JTextField oilfilter;
    private javax.swing.JTextField oilfiltercode;
    private javax.swing.JTextField oilpack;
    private javax.swing.JTextField oils;
    private javax.swing.JTextField penetratingoil;
    private javax.swing.JTextField poweroil;
    private javax.swing.JTextField pr10;
    private javax.swing.JTextField pr11;
    private javax.swing.JTextField pr8;
    private javax.swing.JTextField pr9;
    private javax.swing.JTextField radiatorcoolant;
    private javax.swing.JTextField radiatorflush;
    private javax.swing.JTextField servieid;
    private javax.swing.JTextField total;
    private javax.swing.JTextField underwash;
    private javax.swing.JTextField vacuumcleaning;
    private javax.swing.JTextField vehicle;
    private javax.swing.JTextField vehiclenumber;
    // End of variables declaration//GEN-END:variables
    
}
