
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;

/*
 * customer.java
 *
 * Created on March 6, 2010, 10:41 AM
 */
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import newpackage.DB;
import newpackage.DB;
import newpackage.Handle;



/**
 *
 * @author  Hansa
 */
public class customer extends javax.swing.JFrame {
    JTextField tf;
    /** Creates new form customer */
    public customer() throws ClassNotFoundException {
        try {

            initComponents();
            setSize(785,414);
            customer();
            jTable1.setSelectionMode(0);
            setLocationRelativeTo(null);
            jlist();

            ResultSet rst = Handle.getData(DB.connect(), "select distinct vehicle from airconfilters order by vehicle");
            Connection con = DB.connect();
            
             while (rst.next()){
        jComboBox1.addItem(rst.getString(1));
             }
            
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       
    }
        
    
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customers");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 250, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 250, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 250, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 250, -1));

        jLabel1.setText("Customer ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel2.setText("Customer Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, -1));

        jLabel3.setText("Date of Birth");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, -1, -1));

        jLabel4.setText("NIC Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, -1, -1));

        jLabel5.setText("Vehicle");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 520, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add_user.png"))); // NOI18N
        jButton2.setText("  Add New Customer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 180, 50));

        jComboBox1.setEditable(true);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 520, 250, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 370, 30, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Customer Name", "DOB", "NIC", "Vehicle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 740, 300));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_user.png"))); // NOI18N
        jButton1.setText(" Create Customer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 160, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_cancel.png"))); // NOI18N
        jButton4.setText("   Close");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 150, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/remove_user.png"))); // NOI18N
        jButton3.setText("Remove Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 160, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 760, 370));

        jLabel7.setText("eg. 1990-06-04");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, -1, -1));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_cancel.png"))); // NOI18N
        jButton5.setText("    Cancel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 180, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jTextField1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Customer ID annot Be Empty","Customer ID Required",JOptionPane.OK_OPTION);
        }else if(jTextField2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Customer Name annot Be Empty","Customer Name Required",JOptionPane.OK_OPTION);
        }else if(jComboBox1.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(this,"Customer Vehivle cannot Be Empty","Customer Vehicle Required",JOptionPane.OK_OPTION);
        }else{
            addCustomer();
        }
        jTextField1.setText("");
         jTextField2.setText("");
          jTextField3.setText("");
           jTextField4.setText("");
           jButton1.setEnabled(true);
        setSize(780,410);
        setLocationRelativeTo(null);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(jTable1.isRowSelected(jTable1.getSelectedRow())){
            int y = JOptionPane.showConfirmDialog(this,"Are You Sure Want To Delete Selected Employee","Confirm to Delete",JOptionPane.YES_NO_OPTION);
        if(y==0){
            removeCustomer();
        }   
            
            
            
        }else{
            JOptionPane.showMessageDialog(this,"Please Select a Customer To Delete","Select a Customer",JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setSize(780,580);
        jButton1.setEnabled(false);
        setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
       jTextField3.setText("");
       jTextField4.setText("");
       jButton1.setEnabled(true);
        setSize(785,414);
         setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton5ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new customer().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
    void customer(){
        try {
            ResultSet rst=Handle.getData(DB.connect(), "select * from customer");
            Connection con=DB.connect();
            
            DefaultTableModel dt0 = (DefaultTableModel) jTable1.getModel();

            int rw = dt0.getRowCount();
            for (int i = 0; i < rw; i++) {
                dt0.removeRow(0);
            }

            while (rst.next()) {
                Object[] ob = {rst.getString(1),  rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5)};
                dt0.addRow(ob);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    void addCustomer(){
       try{
   
        String s[] ={jTextField1.getText(),jTextField2.getText(),jTextField3.getText(),jTextField4.getText(),jComboBox1.getSelectedItem().toString()};    
        Handle.setData(DB.connect(), "insert into customer(customerid,customername,customerdob,customernic,customervehicle) values('"+s[0]+"' , '"+s[1]+"' , '"+s[2]+"','"+s[3]+"' , '"+ s[4]+ " ')");
        Connection con=DB.connect();

        customer();
        }catch(Exception e){
          // e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Incorrect Data Inputs","Please Check Out",JOptionPane.OK_CANCEL_OPTION);
        }
    }
    
    void removeCustomer(){
        try{ 
        
            String id = jTable1.getValueAt(jTable1.getSelectedRow(),0)+"";
            Handle.setData(DB.connect(),"delete from customer where customerid = '"+ id + "' " );
            Connection con=DB.connect();
            
            customer();
            }catch(Exception e){
                e.printStackTrace();
            }
    }
    
    void jlist(){
    tf =  (JTextField) jComboBox1.getEditor().getEditorComponent();
    tf.addKeyListener(new KeyAdapter() {
       
            
            @Override
        public void keyReleased(KeyEvent evt){
                try {

                    String s = tf.getText();

                    ResultSet rst=Handle.getData(DB.connect(), "select customervehicle from customer where customervehicle like'"+s+"%'");
                    Connection con=(Connection) DB.connect();
                    
                    jComboBox1.removeAllItems();
                    while (rst.next()){
                    jComboBox1.addItem(rst.getString(1));
                    }
                    
                    
                    int rw=jComboBox1.getMaximumRowCount();
                    
                    if(rw>5){
                    jComboBox1.setMaximumRowCount(5);
                    }else{
                    jComboBox1.setMaximumRowCount(rw);
                    }
                            
                            
                    if(s.isEmpty()||evt.getKeyCode()==KeyEvent.VK_ENTER){
                   jComboBox1.hidePopup();
                   }else{
                    jComboBox1.showPopup();
                    }
                    
                    
                    
                    jComboBox1.setSelectedItem(s);
                            
                            
          
                            
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(customer.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } 
    });
    
    }
    
         
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    
}
