
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * EditFilters.java
 *
 * Created on February 24, 2010, 4:48 AM
 */
import newpackage.DB;
import newpackage.Handle;



/**
 *
 * @author  Dim
 */
public class EditFilters extends javax.swing.JFrame {
    CheckStock02 cs2;
    JTextField tf;
    /** Creates new form EditFilters */
    public EditFilters(CheckStock02 cs) {
        try {

            initComponents();
            setLocationRelativeTo(null);
            cs2 = cs;
            vehicle();

            ResultSet rst = Handle.getData(DB.connect(), "select distinct vehicle from airconfilters");
            Connection con = DB.connect();
            
            while (rst.next()) {
                jComboBox1.addItem(rst.getString(1));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(EditFilters.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(EditFilters.class.getName()).log(Level.SEVERE, null, ex);
        }
            
       
       
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Filter");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jRadioButton1.setText("Airon Filter");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Air Filter");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Fuel Filter");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Oil Filter");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jRadioButton1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 30));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 220, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 218, -1));

        jTextField5.setText("0");
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 218, -1));

        jTextField6.setText("0");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 218, -1));

        jLabel1.setText("Item Code");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 139, -1));

        jLabel3.setText("Vehicle Model");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 139, 20));

        jLabel4.setText("Vehicle Application");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 139, 20));

        jLabel5.setText("Unit Price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 139, 20));

        jLabel6.setText("Quantity on Hand");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 139, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_cancel.png"))); // NOI18N
        jButton1.setText("  Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 251, -1, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edit_add.png"))); // NOI18N
        jButton2.setText("  Add");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 251, 100, 40));

        jComboBox1.setEditable(true);
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 218, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 40, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

      
        if(jTextField1.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Item Code Cannot be Empty","Item Code Required",JOptionPane.OK_OPTION);
       }else{
           if(jRadioButton1.isSelected()){
            addairconfilter();
        }else if(jRadioButton2.isSelected()) {
            addairfilter();
        }else if(jRadioButton3.isSelected()) {
            addfuelfilter();
        }else if(jRadioButton4.isSelected()) {
            addoilfilter();
        }
            dispose();
       }
        
       
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
     
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
           jRadioButton2.setSelected(false);
           jRadioButton3.setSelected(false);
           jRadioButton4.setSelected(false);
           jButton2.setEnabled(true);
           
           if(jRadioButton1.isSelected()){
               jButton2.setEnabled(true);
           }else{
               jButton2.setEnabled(false);
           }
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
           jRadioButton1.setSelected(false);
           jRadioButton3.setSelected(false);
           jRadioButton4.setSelected(false);
           jButton2.setEnabled(true);
           
           if(jRadioButton2.isSelected()){
               jButton2.setEnabled(true);
           }else{
               jButton2.setEnabled(false);
           }
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
           jRadioButton1.setSelected(false);
           jRadioButton2.setSelected(false);
           jRadioButton4.setSelected(false);
           jButton2.setEnabled(true);
           
           if(jRadioButton3.isSelected()){
               jButton2.setEnabled(true);
           }else{
               jButton2.setEnabled(false);
           }
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
           jRadioButton1.setSelected(false);
           jRadioButton2.setSelected(false);
           jRadioButton3.setSelected(false);
           jButton2.setEnabled(true);
           
           if(jRadioButton4.isSelected()){
               jButton2.setEnabled(true);
           }else{
               jButton2.setEnabled(false);
           }
    }//GEN-LAST:event_jRadioButton4ActionPerformed
    
    
     void vehicle(){
    tf= (JTextField) jComboBox1.getEditor().getEditorComponent();
    tf.addKeyListener(new KeyAdapter() {
       
            @Override
        public void keyReleased(KeyEvent evt){
                try {

                    String s = tf.getText();
                    ResultSet rst=Handle.getData(DB.connect(), "select distinct vehicle from airfilters where vehicle like'"+s+"%'");
                    Connection con = DB.connect();
                   
                    jComboBox1.removeAllItems();
                    while (rst.next()){
                    jComboBox1.addItem(rst.getString(1));
                    }
                    
                    
                    int rw=jComboBox1.getMaximumRowCount();
                    
                    if(rw>5){
                    jComboBox1.setMaximumRowCount(5);
                    }else{
                    jComboBox1.setMaximumRowCount(rw);
                    }
                            
                            
                    if(s.isEmpty()||evt.getKeyCode()==KeyEvent.VK_ENTER){
                   jComboBox1.hidePopup();
                   }else{
                    jComboBox1.showPopup();
                    }
                    
                    
                    
                    jComboBox1.setSelectedItem(s);
                            
                            
          
                            
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(EditFilters.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(EditFilters.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } 
    });
    
    }
     
      
    void addairconfilter(){
        
        
       try{
   
        String s[] ={jTextField1.getText(),jComboBox1.getSelectedItem().toString(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()};    
        Handle.setData(DB.connect(), "insert into airconfilters(airconfiltercode,vehicle,vehicleapp,unitprice,qtyonhand) values('"+s[0]+"' , '"+s[1]+"' , '"+s[2]+"','"+s[3]+"' , '"+ s[4]+ " ')");
        Connection con=DB.connect();

       
        }catch(Exception e){
          
            JOptionPane.showConfirmDialog(this,"Incorrect Data Input. Please Check and Try Again","Check Out",JOptionPane.OK_OPTION,2);
        }
    }
    
     void addairfilter(){
        
        
       try{
   
        String s[] ={jTextField1.getText(),jComboBox1.getSelectedItem().toString(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()};    
        Handle.setData(DB.connect(), "insert into airfilters(airfiltercode,vehicle,vehicleapp,unitprice,qtyonhand) values('"+s[0]+"' , '"+s[1]+"' , '"+s[2]+"','"+s[3]+"' , '"+ s[4]+ " ')");
        Connection con=DB.connect();

       
        }catch(Exception e){
           JOptionPane.showConfirmDialog(this,"Incorrect Data Input. Please Check and Try Again","Check Out",JOptionPane.OK_OPTION,2);
        }
    }
     
       void addfuelfilter(){
        
        
       try{
   
        String s[] ={jTextField1.getText(),jComboBox1.getSelectedItem().toString(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()};    
        Handle.setData(DB.connect(), "insert into fuelfilters(fuelfiltercode,vehicle,vehicleapp,unitprice,qtyonhand) values('"+s[0]+"' , '"+s[1]+"' , '"+s[2]+"','"+s[3]+"' , '"+ s[4]+ " ')");
        Connection con=DB.connect();

       
        }catch(Exception e){
           JOptionPane.showConfirmDialog(this,"Incorrect Data Input. Please Check and Try Again","Check Out",JOptionPane.OK_OPTION,2);
        }
    }
       
         void addoilfilter(){
        
        
       try{
   
        String s[] ={jTextField1.getText(),jComboBox1.getSelectedItem().toString(),jTextField4.getText(),jTextField5.getText(),jTextField6.getText()};    
        Handle.setData(DB.connect(), "insert into oilfilters(oilfiltercode,vehicle,vehicleapp,unitprice,qtyonhand) values('"+s[0]+"' , '"+s[1]+"' , '"+s[2]+"','"+s[3]+"' , '"+ s[4]+ " ')");
        Connection con=DB.connect();

       
        }catch(Exception e){
           JOptionPane.showConfirmDialog(this,"Incorrect Data Input. Please Check and Try Again","Check Out",JOptionPane.OK_OPTION,2);
        }
    }
     
     
    /**
     * @param args the command line arguments
     */
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
    
}
