
import java.sql.Connection;

/*
 * inpacks.java
 *
 * Created on February 23, 2010, 2:49 PM
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import newpackage.DB;
import newpackage.Handle;



/**
 *
 * @author  Hans 2010
 */
public class inpacks extends javax.swing.JFrame {
    String pk;
    /** Creates new form inpacks */
    public inpacks(String s) {
        initComponents();
        setLocationRelativeTo(null);
        jTable1.setSelectionMode(0);
        pk =s;
        System.out.println(pk);
        ipDet1();
        jLabel1.setText(pk);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Oil Packs");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pack Size", "Unit Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane1.addTab("In Packs", jScrollPane1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 700, 420));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 500, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel2.setText("Oil Type");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 80, 30));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 490, 30, 80));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 140, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
 
    
   void ipDet1(){
        try {
            ResultSet rst=Handle.getData(DB.connect(), "select * from oils where pdnmngd = '" + pk + "'");
            Connection con=DB.connect();

            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

            int rw = dt.getRowCount();
            for (int i = 0; i < rw; i++) {
                dt.removeRow(0);
            }
            
            rst.next();
            for(int i=4; i<rst.getMetaData().getColumnCount()+1; i++){
            Object ob[] = new Object[2];
            ob[0] = rst.getMetaData().getColumnName(i);
            ob[1] =  rst.getString(i);
            dt.addRow(ob);
           if( (dt.getValueAt( dt.getRowCount()-1,1)== null) || (dt.getValueAt( dt.getRowCount()-1,1).equals("0.00"))    ){
              dt.removeRow(dt.getRowCount()-1);
             }
            
            }
            
            
            
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }
            

    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
