
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;

/*
 * Service.java
 *
 * Created on March 2, 2010, 2:38 PM
 */
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import newpackage.DB;
import newpackage.Handle;



/**
 *
 * @author  Dim
 */
public class Service extends javax.swing.JFrame {
    public String num;
     SV02 s2;
    String a1;
    String a2;
    String a3;
    String a4;
    JTextField tf;
    Timer t;
    
    /** Creates new form Service */
    public Service() {
        try {
            initComponents();
            refresh();
            setSize(1000, 410);

            setLocationRelativeTo(null);

            jButton1.setEnabled(false);
            custname();
            jTable1.setSelectionMode(0);

            ResultSet rst = Handle.getData(DB.connect(), "select customername from customer order by customername");
            Connection con = DB.connect();
                //jComboBox1.addItem("<select or Type customer name>");
            while (rst.next()) {
                jComboBox1.addItem(rst.getString(1));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void search(String a){
        num = a;
        jTextField4.setText(num);
        jButton4.doClick();
        
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField4 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jSpinner3 = new javax.swing.JSpinner();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Services Details");
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1000, 410));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Services"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ServiceID", "Customer Name", "Date", "Vehicle Number", "Vehicle", "KM", "FuelFilter Code", "OilFilter Code", "AirFilter Code", "AirconFilter Code", "Oils", "Packs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/17.png"))); // NOI18N
        jButton4.setText("Search by Vehicle Number");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Delete  16.png"))); // NOI18N
        jButton2.setText("Remove Service");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gloss PNGMacromedia_Shockwave.png"))); // NOI18N
        jButton5.setText("   Show all");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/44444444.png"))); // NOI18N
        jButton3.setText("   Check Bill");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/3D GEARS GEAR11.png"))); // NOI18N
        jButton6.setText("Create Service");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 980, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Create Service"));

        jLabel10.setText("Oils");
        jLabel10.setEnabled(false);

        jLabel11.setText("KM");
        jLabel11.setEnabled(false);

        jTextField3.setEnabled(false);

        jComboBox5.setEnabled(false);

        jComboBox4.setEnabled(false);

        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jComboBox6.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "TOYOTA", "NISSAN", "MITSUBISHI", "MAZDA", "DAIHATSU", "HONDA", "SUBARU", "SUZUKI", "ISUZU", "HINO", "AUDI" }));
        jComboBox2.setEnabled(false);
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jTextField2.setEnabled(false);

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(2010), Integer.valueOf(2010), null, Integer.valueOf(1)));
        jSpinner1.setEnabled(false);

        jSpinner2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jSpinner2.setEnabled(false);

        jSpinner3.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        jSpinner3.setEnabled(false);

        jComboBox1.setEditable(true);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<select or Type customer name>" }));
        jComboBox1.setAutoscrolls(true);
        jComboBox1.setEnabled(false);
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox1MouseEntered(evt);
            }
        });

        jTextField1.setEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jComboBox7.setAutoscrolls(true);
        jComboBox7.setEnabled(false);
        jComboBox7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox7MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox7MousePressed(evt);
            }
        });
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });

        jLabel4.setText("Vehicle Number");
        jLabel4.setEnabled(false);

        jLabel3.setText("Date");
        jLabel3.setEnabled(false);

        jComboBox8.setEnabled(false);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/plus_symbol.png"))); // NOI18N
        jButton1.setText("   Add Service");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Vehicle");
        jLabel5.setEnabled(false);

        jLabel1.setText("Service ID");
        jLabel1.setEnabled(false);

        jLabel2.setText("Customer Name");
        jLabel2.setEnabled(false);

        jLabel6.setText("Fuel Filter");
        jLabel6.setEnabled(false);

        jLabel7.setText("Oil Filter");
        jLabel7.setEnabled(false);

        jLabel8.setText("Air Filter");
        jLabel8.setEnabled(false);

        jLabel9.setText("Aircon Filter");
        jLabel9.setEnabled(false);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/button_cancel.png"))); // NOI18N
        jButton7.setText("    Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, 0, 266, Short.MAX_VALUE)
                            .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 226, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                        .addGap(29, 29, 29))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 950, 360));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 750, 40, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int x = JOptionPane.showConfirmDialog(this,"Are You Sure Want to Remove Selected Service?","Remove Selected",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

        if (x==0){
            removeService();
        }
       jButton3.setEnabled(false);
           
    }//GEN-LAST:event_jButton2ActionPerformed
       
       
    

            private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
            String[] id = {(jTable1.getValueAt(jTable1.getSelectedRow(), 0) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 1) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 2) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 3) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 4) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 5) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 6) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 7) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 8) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 9) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 10) + ""),(jTable1.getValueAt(jTable1.getSelectedRow(), 11) + "")};//GEN-LAST:event_jButton3ActionPerformed
            Bill b = new Bill(id);
            b.setVisible(true);
        
            }


            private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            num = jTextField4.getText();
           try {
            ResultSet rst=Handle.getData(DB.connect(),"select * from service where vehiclenum = '"+num+"'");
            Connection con=DB.connect();

            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

            int rw = dt.getRowCount();
            for (int i = 0; i < rw; i++) {
                dt.removeRow(0);
            }

            while (rst.next()) {
                Object[] ob = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5), rst.getString(6), rst.getString(7), rst.getString(8), rst.getString(9), rst.getString(10), rst.getString(11), rst.getString(12)};
                dt.addRow(ob);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
                        
            String p1=(String) jTable1.getValueAt(0, 5);
            String p2=(String) jTable1.getValueAt(0, 1);
            String p3=(String) jTable1.getValueAt(0, 3);
            String p4=(String) jTable1.getValueAt(0, 2);  
            String p5=(String) jTable1.getValueAt(0, 6);  
            String p6=(String) jTable1.getValueAt(0, 7);  
            String p7=(String) jTable1.getValueAt(0, 8);  
            
             s2=new SV02(p1,p2,p3,p4,p5,p6,p7);
             s2.setVisible(true);
            }//GEN-LAST:event_jButton4ActionPerformed

            private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
                refresh();
                jButton3.setEnabled(false);
            }//GEN-LAST:event_jButton5ActionPerformed

            private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
                jLabel1.setEnabled(true);
                jLabel2.setEnabled(true);
                jLabel3.setEnabled(true);
                jLabel4.setEnabled(true);
                jLabel5.setEnabled(true);
                jLabel6.setEnabled(true);
                jLabel7.setEnabled(true);
                jLabel8.setEnabled(true);
                jLabel9.setEnabled(true);
                jLabel10.setEnabled(true);
                jLabel11.setEnabled(true);
                jTextField1.setEnabled(true);
                jComboBox1.setEnabled(true);
                jSpinner1.setEnabled(true);
                jSpinner2.setEnabled(true);
                jSpinner3.setEnabled(true);
                jTextField2.setEnabled(true);
                jComboBox2.setEnabled(true);
                jTextField3.setEnabled(true);
                jComboBox3.setEnabled(true);
                jComboBox4.setEnabled(true);
                jComboBox5.setEnabled(true);
                jComboBox6.setEnabled(true);
                jComboBox7.setEnabled(true);
                jComboBox8.setEnabled(true);
                jButton1.setEnabled(true);
                setSize(1000,770);
                setLocationRelativeTo(null);
                jButton6.setEnabled(false);
                
            }//GEN-LAST:event_jButton6ActionPerformed

            private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                if (jTextField1.getText().equals("")){
                    JOptionPane.showConfirmDialog(this,"You Must Enter a ServiceID","ServiceID Required",JOptionPane.OK_OPTION,2);
                }else{
            try {

                String[] s = {jTextField1.getText(), jComboBox1.getSelectedItem() + "", jSpinner1.getValue() + "-" + jSpinner2.getValue() + "-" + jSpinner3.getValue(), jTextField2.getText(), jComboBox2.getSelectedItem() + "", jTextField3.getText(), jComboBox3.getSelectedItem() + "", jComboBox4.getSelectedItem() + "", jComboBox5.getSelectedItem() + "", jComboBox6.getSelectedItem() + "", jComboBox7.getSelectedItem() + "", jComboBox8.getSelectedItem() + ""};
                Handle.setData(DB.connect(), "insert into service(serviceid,customerid,date,vehiclenum,vehicle,kmcode,fuelfiltercode,oilfiltercode,airfiltercode,airconfiltercode,pdnmngd,packs) values('" + s[0] + "' , '" + s[1] + "' , '" + s[2] + "','" + s[3] + "' , '" + s[4] + " ', '" + s[5] + " ', '" + s[6] + " ', '" + s[7] + " ', '" + s[8] + " ', '" + s[9] + " ', '" + s[10] + " ', '" + s[11] + " ')");
                Connection con = DB.connect();

                refresh();
            } catch (ClassNotFoundException ex) {
                JOptionPane.showConfirmDialog(this,"There Is Something Wrong","Wrong",JOptionPane.OK_OPTION,2);
            } catch (SQLException ex) {
               JOptionPane.showConfirmDialog(this,"There Is Something Wrong","Wrong",JOptionPane.OK_OPTION,2);
            }
           
                }
                
                setSize(1000,410);
                setLocationRelativeTo(null);
                jButton6.setEnabled(true);  

               
            }//GEN-LAST:event_jButton1ActionPerformed

            private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
                try {
                    ResultSet rst=Handle.getData(DB.connect(), "select * from oils where pdnmngd = '"+ jComboBox7.getSelectedItem() +"" +"'");
                    Connection con=DB.connect();
                    
                    String[] v = new String[30];
                    jComboBox8.removeAllItems();
                    rst.next();
                    for(int i=0; i<27; i++){
                        
                        jComboBox8.addItem(rst.getMetaData().getColumnName(i+4));
                        
                        if(rst.getString(i+4)==null){
                            jComboBox8.removeItemAt(jComboBox8.getItemCount()-1);
                        }
                        
                    }
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
                }
            }//GEN-LAST:event_jComboBox7ActionPerformed

            private void jComboBox7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MousePressed
                
            }//GEN-LAST:event_jComboBox7MousePressed

            private void jComboBox7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MouseEntered
                
            }//GEN-LAST:event_jComboBox7MouseEntered

            private void jComboBox7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox7MouseClicked
        try {

            ResultSet rst = Handle.getData(DB.connect(), "select * from oils where pdnmngd = '" + jComboBox7.getSelectedItem() + "" + "'");
            Connection con = DB.connect();

            String[] v = new String[30];
            jComboBox8.removeAllItems();
            rst.next();
            for (int i = 0; i < 27; i++) {

                jComboBox8.addItem(rst.getMetaData().getColumnName(i + 4));
                System.out.println(rst.getString(i + 4));
                if (rst.getString(i + 4) == null) {
                    jComboBox8.removeItemAt(jComboBox8.getItemCount() - 1);
                }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }

}//GEN-LAST:event_jComboBox7MouseClicked

private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
if(jTextField1.getText().equals("")){
            jButton1.setEnabled(false);
        }else{
            jButton1.setEnabled(true);
        }
}//GEN-LAST:event_jTextField1KeyReleased

private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
try {
            ResultSet rst=Handle.getData(DB.connect(), "select fuelfiltercode from fuelfilters where vehicle = '"+jComboBox2.getSelectedItem()+""+"' ");
            Connection con=DB.connect();
            jComboBox3.addItem("None");
            ///jComboBox3.removeAllItems();
            while (rst.next()) {
            jComboBox3.addItem(rst.getString(1));
            }
 
            rst=Handle.getData(DB.connect(),"select oilfiltercode from oilfilters where vehicle = '"+jComboBox2.getSelectedItem()+""+"' ");
 
            jComboBox4.addItem("None");
            //jComboBox4.removeAllItems();
            while (rst.next()) {
            jComboBox4.addItem(rst.getString(1));
            }
 
             rst=Handle.getData(DB.connect(),"select airfiltercode from airfilters where vehicle = '"+jComboBox2.getSelectedItem()+""+"' ");
 
             jComboBox5.addItem("None");
            //jComboBox5.removeAllItems();
            while (rst.next()) {
            jComboBox5.addItem(rst.getString(1));
            }
 
             rst=Handle.getData(DB.connect(),"select airconfiltercode from airconfilters where vehicle = '"+jComboBox2.getSelectedItem()+""+"' ");
 
             jComboBox6.addItem("None");
            //jComboBox6.removeAllItems();
            while (rst.next()) {
            jComboBox6.addItem(rst.getString(1));
            }
 
            rst=Handle.getData(DB.connect(),"select pdnmngd from oils");
 
     //       jComboBox7.addItem("None");
            //jComboBox7.removeAllItems();
            while (rst.next()) {
            jComboBox7.addItem(rst.getString(1));
            }
 
        } catch (SQLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jComboBox2ActionPerformed

private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
 
}//GEN-LAST:event_jComboBox2MouseClicked

private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
 
}//GEN-LAST:event_jComboBox3ActionPerformed

private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
   if(jTable1.isRowSelected(jTable1.getSelectedRow())){
       jButton3.setEnabled(true);
       jButton2.setEnabled(true);

   }
}//GEN-LAST:event_jTable1MousePressed

private void jComboBox1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseEntered
    
}//GEN-LAST:event_jComboBox1MouseEntered

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    setSize(1000, 410);
    setLocationRelativeTo(null);
    jButton6.setEnabled(true);
}//GEN-LAST:event_jButton7ActionPerformed
            
    
    void refresh(){
        try {

            ResultSet rst=Handle.getData(DB.connect(),"select * from service");
            Connection con=DB.connect();
            
            DefaultTableModel dt = (DefaultTableModel) jTable1.getModel();

            int rw = dt.getRowCount();
            for (int i = 0; i < rw; i++) {
                dt.removeRow(0);
            }

            while (rst.next()) {
                Object[] ob = {rst.getString(1), rst.getString(2), rst.getString(3), rst.getString(4), rst.getString(5), rst.getString(6), rst.getString(7), rst.getString(8), rst.getString(9), rst.getString(10), rst.getString(11), rst.getString(12)};
                dt.addRow(ob);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
     void removeService(){
        try{


        
            String id = jTable1.getValueAt(jTable1.getSelectedRow(),0)+"";
            Handle.setData(DB.connect(),"delete from service where serviceid = '"+ id + "' ");
            Connection con=DB.connect();
            
            
            
            refresh();
            }catch(Exception e){
                e.printStackTrace();
            }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Service().setVisible(true);
            }
        });
    }
    
    void custname(){
    tf =  (JTextField) jComboBox1.getEditor().getEditorComponent();
    tf.addKeyListener(new KeyAdapter() {
       
            
            @Override
        public void keyReleased(KeyEvent evt){
                try {

                    String s = tf.getText();

                    ResultSet rst=Handle.getData(DB.connect(), "select customername from customer where customername like'"+s+"%'");
                    Connection con= DB.connect();
                  
                    jComboBox1.removeAllItems();
                    while (rst.next()){
                    jComboBox1.addItem(rst.getString(1));
                    }
                    
                    
                    int rw=jComboBox1.getMaximumRowCount();
                    
                    if(rw>5){
                    jComboBox1.setMaximumRowCount(5);
                    }else{
                    jComboBox1.setMaximumRowCount(rw);
                    }
                            
                    if(s.isEmpty()||evt.getKeyCode()==KeyEvent.VK_ENTER){
                   jComboBox1.hidePopup();
                   }else{
                    jComboBox1.showPopup();
                    }
                    
                    jComboBox1.setSelectedItem(s);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Service.class.getName()).log(Level.SEVERE, null, ex);
                }
            
        } 
    });
    
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
    
}
