
import javax.swing.JOptionPane;





/**
 *
 * @author  Menik
 */
public class SV01 extends javax.swing.JFrame {
    SV02 ltd;
    Home01 home;
    /** Creates new form searchVehicle */
    public SV01() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        svhome = new javax.swing.JButton();
        svok = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Vehicle by Number");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter Vehicle Number:-");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 280, 30));

        svhome.setFont(new java.awt.Font("Tahoma", 1, 14));
        svhome.setForeground(new java.awt.Color(0, 0, 255));
        svhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.png"))); // NOI18N
        svhome.setText("  HOME");
        svhome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        svhome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        svhome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svhomeActionPerformed(evt);
            }
        });
        jPanel1.add(svhome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 120, 40));

        svok.setFont(new java.awt.Font("Tahoma", 1, 14));
        svok.setForeground(new java.awt.Color(0, 0, 255));
        svok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/17  32.png"))); // NOI18N
        svok.setText("   Search");
        svok.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        svok.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        svok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                svokActionPerformed(evt);
            }
        });
        jPanel1.add(svok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void svokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svokActionPerformed
        if(jTextField1.getText().equals("")){
            
            JOptionPane.showConfirmDialog(this,"Text Field is Empty. Please Type a Number to Search", "Empty Text Field",JOptionPane.OK_OPTION,2);
        }else{
            String num = jTextField1.getText();
            Service se = new Service();
            se.setVisible(true);
            se.search(num);
            dispose();
        }
       
}//GEN-LAST:event_svokActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased

        

       
    }//GEN-LAST:event_jTextField1KeyReleased

    private void svhomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_svhomeActionPerformed
        
       dispose();
}//GEN-LAST:event_svhomeActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
      
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
       
    }//GEN-LAST:event_jTextField1KeyTyped
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                    new SV01().setVisible(true);
               
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton svhome;
    private javax.swing.JButton svok;
    // End of variables declaration//GEN-END:variables
    
}
